// Twenty CRM connector — REST API with Bearer token auth
// Replaces SuiteCRM connector. No session management, no MD5, no SQL queries.

function getEnv(name, fallback = '') {
  return process.env[name] || fallback;
}

function twentyBaseUrl() {
  return getEnv('TWENTY_BASE_URL', '').replace(/\/+$/, '');
}

function hasTwentyConfig() {
  return Boolean(twentyBaseUrl() && getEnv('TWENTY_API_KEY'));
}

async function twentyFetch(method, path, body, timeoutMs = 15000) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const opts = {
      method,
      headers: {
        Authorization: `Bearer ${getEnv('TWENTY_API_KEY')}`,
        'Content-Type': 'application/json',
      },
      signal: controller.signal,
    };
    if (body && method !== 'GET') opts.body = JSON.stringify(body);
    const response = await fetch(`${twentyBaseUrl()}${path}`, opts);
    if (!response.ok) {
      const text = await response.text();
      throw new Error(`Twenty API ${method} ${path} failed: ${response.status} ${text}`);
    }
    return response.json();
  } finally {
    clearTimeout(timeout);
  }
}

function toInt(v, fallback = 0) {
  const n = parseInt(v, 10);
  return Number.isFinite(n) ? n : fallback;
}

function igHandle(v) {
  if (!v) return '';
  return String(v).replace(/^https?:\/\/(www\.)?instagram\.com\//, '').replace(/\/.*$/, '').replace(/^@/, '');
}

// Map pipeline contact to Twenty People object fields.
// Standard fields use Twenty's built-in schema.
// Custom fields use API names generated by Twenty (placeholder names below —
// finalize after creating custom fields in Step 6).
function contactToTwentyPerson(contact) {
  const email = contact.Email || contact['Work Email'] || '';
  const linkedinUrl = contact['LinkedIn Profile'] || contact.linkedin_url || '';

  return {
    name: {
      firstName: contact['First Name'] || '',
      lastName: contact['Last Name'] || '',
    },
    emails: {
      primaryEmail: email,
    },
    company: contact['Company Name'] || '',
    jobTitle: contact.job_title || '',
    linkedinLink: { primaryLinkUrl: linkedinUrl, primaryLinkLabel: 'LinkedIn' },
    // Custom fields — update API names after Twenty custom field creation
    icpScore: toInt(contact.icp_score),
    icpTier: contact.icp_tier || '',
    triggerScore: toInt(contact.trigger_score),
    hookText: contact.hook_text || '',
    hookVariant: contact.hook_variant || '',
    hookSource: contact.hook_source || '',
    igUsername: igHandle(contact['IG handle'] || contact.ig_username || ''),
    linkedinHeadline: (contact.linkedin_headline || '').substring(0, 255),
    linkedinDaysSincePost: toInt(contact.linkedin_days_since_post, 999),
    linkedinRecentTopic: (contact.linkedin_recent_topic || '').substring(0, 50),
    igFollowers: toInt(contact.ig_followers),
    igDaysSincePost: toInt(contact.ig_days_since_post, 999),
    externalLeadId: contact.external_lead_id || '',
    funnelStage: contact.funnel_stage || 'New',
    leadSource: contact.source_primary || 'Clay',
  };
}

async function findPersonByEmail(email) {
  const encoded = encodeURIComponent(
    JSON.stringify({ and: [{ emails: { primaryEmail: { eq: email } } }] })
  );
  const result = await twentyFetch('GET', `/api/objects/people?filter=${encoded}&limit=1`);
  const records = result?.data?.people || result?.data || [];
  return Array.isArray(records) && records.length > 0 ? records[0] : null;
}

async function upsertPerson(contact) {
  const email = contact.Email || contact['Work Email'] || '';
  const existing = await findPersonByEmail(email);
  const body = contactToTwentyPerson(contact);

  if (existing) {
    await twentyFetch('PATCH', `/api/objects/people/${existing.id}`, body);
    return { action: 'updated', id: existing.id };
  }
  const created = await twentyFetch('POST', '/api/objects/people', body);
  return { action: 'created', id: created?.data?.id || created?.id || 'unknown' };
}

export async function syncContactsToTwenty(contacts, options = {}) {
  const dryRun = String(process.env.CRM_DRY_RUN || 'false').toLowerCase() === 'true';
  const maxPerRun = Number(process.env.CRM_MAX_UPSERT_PER_RUN || options.maxPerRun || 0);

  if (!hasTwentyConfig()) {
    return {
      mode: 'twenty-not-configured',
      created: 0,
      updated: 0,
      errors: 0,
      skipped: contacts.length,
      warnings: ['Twenty CRM env vars missing (TWENTY_BASE_URL / TWENTY_API_KEY)'],
    };
  }

  const limited = maxPerRun > 0 ? contacts.slice(0, maxPerRun) : contacts;

  if (dryRun) {
    return {
      mode: 'twenty-dry-run',
      created: 0,
      updated: 0,
      errors: 0,
      skipped: contacts.length - limited.length,
      warnings: [`CRM_DRY_RUN=true, would process ${limited.length} contacts`],
    };
  }

  let created = 0;
  let updated = 0;
  let errors = 0;
  let skipped = 0;
  const warnings = [];

  for (const contact of limited) {
    const email = contact.Email || contact['Work Email'] || '';
    if (!email || !email.includes('@')) {
      skipped += 1;
      continue;
    }
    try {
      const result = await upsertPerson(contact);
      if (result.action === 'created') created += 1;
      if (result.action === 'updated') updated += 1;
    } catch (error) {
      errors += 1;
      if (warnings.length < 30) warnings.push(error.message);
    }
  }

  return {
    mode: 'twenty-api',
    created,
    updated,
    errors,
    skipped: skipped + (contacts.length - limited.length),
    warnings,
  };
}

export { hasTwentyConfig };
